//settings
const SET_CRYPTO_CURRENCY_UNIT = 'SET_CRYPTO_CURRENCY_UNIT'
const SET_LEGAL_CURRENCY_UNIT = 'SET_LEGAL_CURRENCY_UNIT'

//account
const SET_ACCOUNT = 'SET_ACCOUNT'

export { SET_CRYPTO_CURRENCY_UNIT, SET_LEGAL_CURRENCY_UNIT, SET_ACCOUNT }
