export default {
  SET_ACCOUNT: 'SET_ACCOUNT',
  SET_LEGAL_CURRENCY_UNIT: 'SET_LEGAL_CURRENCY_UNIT',
  SET_BTC_UNIT: 'SET_BTC_UNIT',
  SET_ETH_UNIT: 'SET_ETH_UNIT',
  SET_EOS_UNIT: 'SET_EOS_UNIT',
  SET_ACCOUNT_CRYPTO_CURRENCY_UNIT: 'SET_ACCOUNT_CRYPTO_CURRENCY_UNIT'
}
